//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 08:06:25 PM GMT 
//


package com.rider.ddswrapper.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainParticipant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DomainParticipant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DomainParticipantName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DomainId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="QoSLibrary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QoSProfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoggerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Publisher" type="{}Publisher" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Subscriber" type="{}Subscriber" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Requester" type="{}Requester" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Replier" type="{}Replier" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomainParticipant", propOrder = {
    "domainParticipantName",
    "domainId",
    "qoSLibrary",
    "qoSProfile",
    "loggerName",
    "publisher",
    "subscriber",
    "requester",
    "replier"
})
public class DomainParticipant {

    @XmlElement(name = "DomainParticipantName", required = true)
    protected String domainParticipantName;
    @XmlElement(name = "DomainId")
    protected int domainId;
    @XmlElement(name = "QoSLibrary", required = true)
    protected String qoSLibrary;
    @XmlElement(name = "QoSProfile", required = true)
    protected String qoSProfile;
    @XmlElement(name = "LoggerName")
    protected String loggerName;
    @XmlElement(name = "Publisher")
    protected List<Publisher> publisher;
    @XmlElement(name = "Subscriber")
    protected List<Subscriber> subscriber;
    @XmlElement(name = "Requester")
    protected List<Requester> requester;
    @XmlElement(name = "Replier")
    protected List<Replier> replier;

    /**
     * Gets the value of the domainParticipantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainParticipantName() {
        return domainParticipantName;
    }

    /**
     * Sets the value of the domainParticipantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainParticipantName(String value) {
        this.domainParticipantName = value;
    }

    /**
     * Gets the value of the domainId property.
     * 
     */
    public int getDomainId() {
        return domainId;
    }

    /**
     * Sets the value of the domainId property.
     * 
     */
    public void setDomainId(int value) {
        this.domainId = value;
    }

    /**
     * Gets the value of the qoSLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQoSLibrary() {
        return qoSLibrary;
    }

    /**
     * Sets the value of the qoSLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQoSLibrary(String value) {
        this.qoSLibrary = value;
    }

    /**
     * Gets the value of the qoSProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQoSProfile() {
        return qoSProfile;
    }

    /**
     * Sets the value of the qoSProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQoSProfile(String value) {
        this.qoSProfile = value;
    }

    /**
     * Gets the value of the loggerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoggerName() {
        return loggerName;
    }

    /**
     * Sets the value of the loggerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoggerName(String value) {
        this.loggerName = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publisher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublisher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Publisher }
     * 
     * 
     */
    public List<Publisher> getPublisher() {
        if (publisher == null) {
            publisher = new ArrayList<Publisher>();
        }
        return this.publisher;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscriber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscriber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subscriber }
     * 
     * 
     */
    public List<Subscriber> getSubscriber() {
        if (subscriber == null) {
            subscriber = new ArrayList<Subscriber>();
        }
        return this.subscriber;
    }

    /**
     * Gets the value of the requester property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requester property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequester().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Requester }
     * 
     * 
     */
    public List<Requester> getRequester() {
        if (requester == null) {
            requester = new ArrayList<Requester>();
        }
        return this.requester;
    }

    /**
     * Gets the value of the replier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the replier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReplier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Replier }
     * 
     * 
     */
    public List<Replier> getReplier() {
        if (replier == null) {
            replier = new ArrayList<Replier>();
        }
        return this.replier;
    }

}
