//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 08:06:25 PM GMT 
//


package com.rider.ddswrapper.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Reader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Reader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReaderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TopicName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QoSLibrary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QoSProfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NotificationType" type="{}NotificationType" minOccurs="0"/>
 *         &lt;element name="LoggerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reader", propOrder = {
    "readerName",
    "typeName",
    "topicName",
    "qoSLibrary",
    "qoSProfile",
    "notificationType",
    "loggerName"
})
public class Reader {

    @XmlElement(name = "ReaderName", required = true)
    protected String readerName;
    @XmlElement(name = "TypeName", required = true)
    protected String typeName;
    @XmlElement(name = "TopicName", required = true)
    protected String topicName;
    @XmlElement(name = "QoSLibrary", required = true)
    protected String qoSLibrary;
    @XmlElement(name = "QoSProfile", required = true)
    protected String qoSProfile;
    @XmlElement(name = "NotificationType")
    protected NotificationType notificationType;
    @XmlElement(name = "LoggerName")
    protected String loggerName;

    /**
     * Gets the value of the readerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReaderName() {
        return readerName;
    }

    /**
     * Sets the value of the readerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReaderName(String value) {
        this.readerName = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the topicName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * Sets the value of the topicName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopicName(String value) {
        this.topicName = value;
    }

    /**
     * Gets the value of the qoSLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQoSLibrary() {
        return qoSLibrary;
    }

    /**
     * Sets the value of the qoSLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQoSLibrary(String value) {
        this.qoSLibrary = value;
    }

    /**
     * Gets the value of the qoSProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQoSProfile() {
        return qoSProfile;
    }

    /**
     * Sets the value of the qoSProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQoSProfile(String value) {
        this.qoSProfile = value;
    }

    /**
     * Gets the value of the notificationType property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationType }
     *     
     */
    public NotificationType getNotificationType() {
        return notificationType;
    }

    /**
     * Sets the value of the notificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationType }
     *     
     */
    public void setNotificationType(NotificationType value) {
        this.notificationType = value;
    }

    /**
     * Gets the value of the loggerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoggerName() {
        return loggerName;
    }

    /**
     * Sets the value of the loggerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoggerName(String value) {
        this.loggerName = value;
    }

}
