//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 08:06:25 PM GMT 
//


package com.rider.ddswrapper.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Replier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Replier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LoggerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RequestType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReplyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Replier", propOrder = {
    "replierName",
    "loggerName",
    "requestType",
    "replyType",
    "serviceName"
})
public class Replier {

    @XmlElement(name = "ReplierName", required = true)
    protected String replierName;
    @XmlElement(name = "LoggerName")
    protected String loggerName;
    @XmlElement(name = "RequestType", required = true)
    protected String requestType;
    @XmlElement(name = "ReplyType", required = true)
    protected String replyType;
    @XmlElement(name = "ServiceName", required = true)
    protected String serviceName;

    /**
     * Gets the value of the replierName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplierName() {
        return replierName;
    }

    /**
     * Sets the value of the replierName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplierName(String value) {
        this.replierName = value;
    }

    /**
     * Gets the value of the loggerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoggerName() {
        return loggerName;
    }

    /**
     * Sets the value of the loggerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoggerName(String value) {
        this.loggerName = value;
    }

    /**
     * Gets the value of the requestType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * Sets the value of the requestType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestType(String value) {
        this.requestType = value;
    }

    /**
     * Gets the value of the replyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyType() {
        return replyType;
    }

    /**
     * Sets the value of the replyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyType(String value) {
        this.replyType = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceName(String value) {
        this.serviceName = value;
    }

}
