//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.27 at 08:06:25 PM GMT 
//


package com.rider.ddswrapper.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Subscriber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Subscriber">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubscriberName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QoSLibrary" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="QoSProfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PartitionName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LoggerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reader" type="{}Reader" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Subscriber", propOrder = {
    "subscriberName",
    "qoSLibrary",
    "qoSProfile",
    "partitionName",
    "loggerName",
    "reader"
})
public class Subscriber {

    @XmlElement(name = "SubscriberName", required = true)
    protected String subscriberName;
    @XmlElement(name = "QoSLibrary", required = true)
    protected String qoSLibrary;
    @XmlElement(name = "QoSProfile", required = true)
    protected String qoSProfile;
    @XmlElement(name = "PartitionName")
    protected List<String> partitionName;
    @XmlElement(name = "LoggerName")
    protected String loggerName;
    @XmlElement(name = "Reader")
    protected List<Reader> reader;

    /**
     * Gets the value of the subscriberName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscriberName() {
        return subscriberName;
    }

    /**
     * Sets the value of the subscriberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscriberName(String value) {
        this.subscriberName = value;
    }

    /**
     * Gets the value of the qoSLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQoSLibrary() {
        return qoSLibrary;
    }

    /**
     * Sets the value of the qoSLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQoSLibrary(String value) {
        this.qoSLibrary = value;
    }

    /**
     * Gets the value of the qoSProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQoSProfile() {
        return qoSProfile;
    }

    /**
     * Sets the value of the qoSProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQoSProfile(String value) {
        this.qoSProfile = value;
    }

    /**
     * Gets the value of the partitionName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partitionName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartitionName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPartitionName() {
        if (partitionName == null) {
            partitionName = new ArrayList<String>();
        }
        return this.partitionName;
    }

    /**
     * Gets the value of the loggerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoggerName() {
        return loggerName;
    }

    /**
     * Sets the value of the loggerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoggerName(String value) {
        this.loggerName = value;
    }

    /**
     * Gets the value of the reader property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reader property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReader().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reader }
     * 
     * 
     */
    public List<Reader> getReader() {
        if (reader == null) {
            reader = new ArrayList<Reader>();
        }
        return this.reader;
    }

}
